/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jp.ac.uryukyu.ie.e215750;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

//class GameTest {
//    @Test
//}
